
function Dummy(){

	this.data =
	             {
	                 "data":{
	                    "query":"women",
	                    "results":{
	                       "totalResults":"22",
	                       "results":[
	                          {
	                             "facets":{
	                                "year":"2013",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010250750",
	                             "id":"10010250750",
	                             "title":"The political economy of peacebuilding: the case of women's cooperatives in Nepal"
	                          },
	                          {
	                             "facets":{
	                                "language":"nl",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fhdl.handle.net%2…22%252F30051000500766%253Flocatt%253Dview%253Alevel2&size=LARGE&type=IMAGE",
	                             "id":"/2022005/15F4B4F377AE63E2A7305AB0D3BF334ECE1737E8",
	                             "uri":"http://europeana.eu/resolve/record/2022005/15F4B4F377AE63E2A7305AB0D3BF334ECE1737E8",
	                             "title":"Strikes.Women."
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fmedia.iwm.org.uk…wm%252FmediaLib%252F23%252Fmedia-23686%252Flarge.jpg&size=LARGE&type=IMAGE",
	                             "id":"/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205127690",
	                             "uri":"http://europeana.eu/resolve/record/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205127690",
	                             "title":"WOMEN IN UNIFORM DURING THE FIRST WORLD WARWOMEN IN UNIFORM DURING THE FIRST WORLD WAR"
	                          },
	                          {
	                             "facets":{
	                                "year":"2014",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010252640",
	                             "id":"10010252640",
	                             "title":"Selection and the measured black-white wage gap among young women revisited"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.culturegrid.…urce%252F4284489%252Fstream%252Fthumbnail_image_jpeg&size=LARGE&type=IMAGE",
	                             "id":"/2022329/ADB80643AF9D96886D8DAB61AD312F204040616E",
	                             "uri":"http://europeana.eu/resolve/record/2022329/ADB80643AF9D96886D8DAB61AD312F204040616E",
	                             "title":"photograph"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fmedia.iwm.org.uk…wm%252FmediaLib%252F14%252Fmedia-14208%252Flarge.jpg&size=LARGE&type=IMAGE",
	                             "id":"/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205087103",
	                             "uri":"http://europeana.eu/resolve/record/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205087103",
	                             "title":"WOMEN IN RUSSIA DURING THE FIRST WORLD WARWOMEN IN RUSSIA DURING THE FIRST WORLD WAR"
	                          },
	                          {
	                             "facets":{
	                                "language":"mul",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.nli.ie%252Fglassplates%252Fthumbs%252FCLAR%252FCLAR_146.jpg&size=LARGE&type=IMAGE",
	                             "id":"/92022/D2B985E9E5A8A711EAE0969251560028BF195F0F",
	                             "uri":"http://europeana.eu/resolve/record/92022/D2B985E9E5A8A711EAE0969251560028BF195F0F",
	                             "title":"Women on a beach. Two women, fully dressed with parasols. Two women in bathing suits and hats, running in the foreground"
	                          },
	                          {
	                             "facets":{
	                                "year":"2014",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010346114",
	                             "id":"10010346114",
	                             "title":"Women's empowerment and socio-economic outcomes : impacts of the Andhra Pradesh rural poverty reduction program"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.culturegrid.…urce%252F5053580%252Fstream%252Fthumbnail_image_jpeg&size=LARGE&type=IMAGE",
	                             "id":"/2022359/JR0690_15",
	                             "uri":"http://europeana.eu/resolve/record/2022359/JR0690_15",
	                             "title":"Women\u2019s Institute play"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fmedia.iwm.org.uk…%252FmediaLib%252F359%252Fmedia-359511%252Flarge.jpg&size=LARGE&type=IMAGE",
	                             "id":"/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205314755",
	                             "uri":"http://europeana.eu/resolve/record/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205314755",
	                             "title":"WOMEN IN THE FIRST WORLD WAR 1914-1918WOMEN IN THE FIRST WORLD WAR 1914-1918"
	                          },
	                          {
	                             "facets":{
	                                "year":"2014",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010333289",
	                             "id":"10010333289",
	                             "title":"Selection and the Measured Black-White Wage Gap Among Young Women Revisited"
	                          },
	                          {
	                             "facets":{
	                                "year":"2013",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010206985",
	                             "id":"10010206985",
	                             "title":"A review of quality of work life balance for women employees : a case study of working women in academics"
	                          },
	                          {
	                             "facets":{
	                                "year":"2014",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010345616",
	                             "id":"10010345616",
	                             "title":"The impact of an adolescent girls employment program : the EPAG project in Liberia"
	                          },
	                          {
	                             "facets":{
	                                "year":"1936",
	                                "language":"nl",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fhdl.handle.net%2…22%252F30051000615325%253Flocatt%253Dview%253Alevel2&size=LARGE&type=IMAGE",
	                             "id":"/2022005/4C8D94943428084192BA3150802F783920F894A3",
	                             "uri":"http://europeana.eu/resolve/record/2022005/4C8D94943428084192BA3150802F783920F894A3",
	                             "title":"Turkey conscripts women."
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.culturegrid.…urce%252F5053794%252Fstream%252Fthumbnail_image_jpeg&size=LARGE&type=IMAGE",
	                             "id":"/2022359/JR1894_35A",
	                             "uri":"http://europeana.eu/resolve/record/2022359/JR1894_35A",
	                             "title":"Women\u2019s Institute meeting"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.culturegrid.…urce%252F2162517%252Fstream%252Fthumbnail_image_jpeg&size=LARGE&type=IMAGE",
	                             "id":"/2022323/349E503641804F519905823F112748314D38F12B",
	                             "uri":"http://europeana.eu/resolve/record/2022323/349E503641804F519905823F112748314D38F12B",
	                             "title":"Women at Riddings Foundry"
	                          },
	                          {
	                             "facets":{
	                                "year":"2013",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010209752",
	                             "id":"10010209752",
	                             "title":"Can political empowerment help economic empowerment? : women leaders and female labor force participation in India"
	                          },
	                          {
	                             "facets":{
	                                "year":"2013",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10009769256",
	                             "id":"10009769256",
	                             "title":"A social work study on the effect of family life education on marital satisfaction of women attending in Isfahan Counseling Centers"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fwww.culturegrid.…urce%252F5053361%252Fstream%252Fthumbnail_image_jpeg&size=LARGE&type=IMAGE",
	                             "id":"/2022359/JR0419_32A",
	                             "uri":"http://europeana.eu/resolve/record/2022359/JR0419_32A",
	                             "title":"Tea table at the Women\u2019s Institute jumble sale"
	                          },
	                          {
	                             "facets":{
	                                "year":"2014",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10010343439",
	                             "id":"10010343439",
	                             "title":"The heterogeneous effects of HIV testing"
	                          },
	                          {
	                             "facets":{
	                                "year":"2013",
	                                "language":"de",
	                                "provider":"ZBW"
	                             },
	                             "uri":"http://www.econbiz.de/Record/10009761888",
	                             "id":"10009761888",
	                             "title":"Analysis of impact of microfinance services on business performance of small scale women entrepreneurs in Enugu State, Nigeria"
	                          },
	                          {
	                             "facets":{
	                                "language":"en",
	                                "provider":"Europeana"
	                             },
	                             "previewImage":"http://europeanastatic.eu/api/image?uri=http%253A%252F%252Fmedia.iwm.org.uk…%252FmediaLib%252F345%252Fmedia-345035%252Flarge.jpg&size=LARGE&type=IMAGE",
	                             "id":"/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205077103",
	                             "uri":"http://europeana.eu/resolve/record/2022360/Imperial_War_Museums_http___www_iwm_org_uk_collections_item_object_205077103",
	                             "title":"CIVILIAN WAR PRODUCTION 1914 - 1918: WOMEN IN INDUSTRYBRITAIN'S WAR PRODUCTION 1914 - 1918: WOMEN IN INDUSTRYCIVILIAN WAR PRODUCTION 1914 - 1918: WOMEN IN INDUSTRY"
	                          }
	                       ],
	                       "provider":"Federated"
	                    }
	                 },
	                 "mapping":[
	                    {
	                       "chartname":"timeline",
	                       "visualchannels":[
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"language",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#nominal"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineColor",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"color"
	                          },
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"year",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#quantitative"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineXAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"x-Axis"
	                          },
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"provider",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#nominal"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineYAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"y-Axis"
	                          }
	                       ],
	                       "charturi":"http://eexcess.eu/visualisation-ontologyTimeline"
	                    },
	                    {
	                       "chartname":"timeline",
	                       "visualchannels":[
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"language",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#nominal"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineYAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"y-Axis"
	                          },
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"year",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#quantitative"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineXAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"x-Axis"
	                          },
	                          {
	                             "chartname":"timeline",
	                             "component":{
	                                "facet":"provider",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#nominal"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyTimelineColor",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyTimeline",
	                             "label":"color"
	                          }
	                       ],
	                       "charturi":"http://eexcess.eu/visualisation-ontologyTimeline"
	                    },
	                    {
	                       "chartname":"barchart",
	                       "visualchannels":[
	                          {
	                             "chartname":"barchart",
	                             "component":{
	                                "facet":"keywords",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#nominal"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyBarChartXAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyBarchart",
	                             "label":"x-Axis"
	                          },
	                          {
	                             "chartname":"barchart",
	                             "component":{
	                                "facet":"value",
	                                "datatype":"http://eexcess.eu/visualisation-ontology#quantitative"
	                             },
	                             "name":"http://eexcess.eu/visualisation-ontologyBarChartYAxis",
	                             "charturi":"http://eexcess.eu/visualisation-ontologyBarchart",
	                             "label":"y-Axis"
	                          }
	                       ],
	                       "charturi":"http://eexcess.eu/visualisation-ontologyBarchart"
	                    }
	                 ]
	              };	//end this.data
	


}	//end function